name: wine_inventory
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+13



environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Image handling
  image_cropper: ^8.1.0
  camera: ^0.11.0+2
  image_picker: ^1.0.7
  
  # UI and utilities
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  intl: ^0.20.1
  provider: ^6.1.1
  
  # Firebase packages - using specific versions
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  cached_network_image: ^3.3.1
  # Force specific grpc version to avoid BoringSSL issues
  grpc: ^4.0.1
  
  # Other dependencies
  cupertino_icons: ^1.0.8
  share_plus: ^10.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true